{% set version = "1.4" %}

package:
    name: verboselogs
    version: {{ version }}

source:
    fn: verboselogs-{{ version }}.tar.gz
    url: https://files.pythonhosted.org/packages/cd/b8/d87bbd0eab68c1e13ca7b2a0f38a986ed7f16b006f7bc6115e8043f514fe/verboselogs-1.4.tar.gz
    md5: 811da460e30f3abd51ada927d6da8b48

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    host:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - verboselogs

about:
    home: https://verboselogs.readthedocs.io
    license: MIT
    summary: "Verbose logging level for Python's logging module."
    description: |
      The verboselogs package extends Python’s logging module to add the log 
      levels NOTICE, SPAM, SUCCESS and VERBOSE
    doc_url: https://verboselogs.readthedocs.io
    dev_url: https://github.com/xolox/python-verboselogs
    doc_source_url: https://github.com/xolox/python-verboselogs/tree/master/docs

extra:
    recipe-maintainers:
        - ocefpaf
